# Define a imagem base que será utilizada
FROM python:3.10

# Define o diretório de trabalho dentro do contêiner
WORKDIR /user_service

# Copia o arquivo requirements.txt do diretório local para o diretório /user_service no contêiner
COPY requirements.txt .

# Instala as dependências listadas no arquivo requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Copia todo o conteúdo da pasta user_service do diretório local para a pasta /user_service no contêiner
COPY user_service ./user_service

# Define o comando padrão a ser executado quando o contêiner for iniciado
CMD ["uvicorn", "user_service.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
