version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword

  user_service:
    build:
      context: .
      dockerfile: ./user_service/Dockerfile_user_service
    container_name: user_service
    ports:
      - "8000:8000"
    volumes:
      - ./user_service:/user_service

  auth_service:
    build:
      context: .
      dockerfile: ./auth_service/Dockerfile_auth_service
    container_name: auth_service
    ports:
      - "7000:7000"
    volumes:
      - ./auth_service:/auth_service

volumes:
  mongodb_data:
