# Define a imagem base que será utilizada
FROM python:3.10

# Define o diretório de trabalho dentro do contêiner
WORKDIR /auth_service

# Copia o arquivo requirements.txt do diretório local para o diretório /auth_service no contêiner
COPY auth_service/requirements.txt .

# Instala as dependências listadas no arquivo requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Copia todo o conteúdo da pasta auth_service do diretório local para a pasta /auth_service no contêiner
COPY auth_service ./auth_service

# Define o comando padrão a ser executado quando o contêiner for iniciado
CMD ["uvicorn", "auth_service.main:app", "--host", "0.0.0.0", "--port", "7000", "--reload"]
